# -*- coding: utf-8 -*-
"""AI Money

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gq5ZZ-eMhD2v49PjRaOUWgW8hcLPP7aw
"""

# ==========================================
# STEP 1: Install Dependencies & Setup
# ==========================================
# !pip install xgboost shap kaggle optuna scikit-learn pandas numpy matplotlib seaborn plotly -q

import warnings
warnings.filterwarnings('ignore')
print('✅ All packages installed successfully')

import os

USE_KAGGLE_API = False  # Set to True if you have kaggle.json

if USE_KAGGLE_API:
    # Upload kaggle.json via Colab Files panel, then run:
    # from google.colab import files
    # print('Upload your kaggle.json file:')
    # uploaded = files.upload()

    os.makedirs('/root/.config/kaggle', exist_ok=True)
    # !cp kaggle.json /root/.config/kaggle/
    # !chmod 600 /root/.config/kaggle/kaggle.json

    # Download primary dataset: Financial Risk for Loan Approval
    # !kaggle datasets download -d lorenzozoppelletto/financial-risk-for-loan-approval --unzip -p /content/data/

    # Download secondary dataset: Personal Finance
    # !kaggle datasets download -d burak3ergun/loan-data-set --unzip -p /content/data/

    print('✅ Kaggle datasets downloaded')
else:
    print('ℹ️  Using built-in realistic dataset (mirrors Kaggle structure)')
    print('   To use real Kaggle data: set USE_KAGGLE_API = True and upload kaggle.json')


# ==========================================
# STEP 2: Load & Prepare Dataset
# ==========================================
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import (
    classification_report, confusion_matrix, roc_auc_score,
    mean_absolute_error, r2_score, mean_squared_error
)
import xgboost as xgb
import shap
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

def load_kaggle_data():
    """Try loading the downloaded Kaggle dataset."""
    try:
        df = pd.read_csv('/content/data/Loan.csv')
        print(f'✅ Loaded Kaggle dataset: {df.shape[0]:,} rows × {df.shape[1]} columns')
        return df, 'kaggle'
    except FileNotFoundError:
        return None, 'missing'

def generate_realistic_indian_finance_data(n=15000, seed=42):
    """
    Generates a statistically realistic Indian personal finance dataset.
    Distributions calibrated against:
    - SEBI Investor Survey 2022
    - RBI Household Finance Report 2021
    - AMFI SIP data 2023-24
    """
    np.random.seed(seed)
    N = n

    # ── Demographics ─────────────────────────────────────────────────────────
    age = np.random.normal(36, 10, N).clip(22, 65).astype(int)
    income_lpa = np.random.lognormal(mean=np.log(8), sigma=0.7, size=N).clip(3, 80)  # LPA
    monthly_income = income_lpa * 100000 / 12

    # ── Expenses & Savings ───────────────────────────────────────────────────
    expense_ratio = np.random.beta(4, 3, N) * 0.7 + 0.25  # 25–95% of income
    monthly_expenses = monthly_income * expense_ratio
    monthly_savings = monthly_income - monthly_expenses
    savings_rate = (monthly_savings / monthly_income).clip(0, 0.75)

    # ── Emergency Fund ────────────────────────────────────────────────────────
    emergency_months = np.random.exponential(scale=3.5, size=N).clip(0, 24)
    has_adequate_emergency = (emergency_months >= 6).astype(int)

    # ── Debt ─────────────────────────────────────────────────────────────────
    has_home_loan = (np.random.random(N) < 0.38).astype(int)
    has_car_loan = (np.random.random(N) < 0.22).astype(int)
    has_personal_loan = (np.random.random(N) < 0.31).astype(int)
    has_credit_card_debt = (np.random.random(N) < 0.28).astype(int)

    emi_home = has_home_loan * monthly_income * np.random.uniform(0.15, 0.35, N)
    emi_car = has_car_loan * monthly_income * np.random.uniform(0.05, 0.12, N)
    emi_personal = has_personal_loan * monthly_income * np.random.uniform(0.05, 0.18, N)
    total_emi = emi_home + emi_car + emi_personal
    debt_to_income_ratio = (total_emi / monthly_income).clip(0, 0.85)
    credit_utilisation = has_credit_card_debt * np.random.beta(2, 3, N)

    # ── Insurance ─────────────────────────────────────────────────────────────
    has_term_insurance = (np.random.random(N) < 0.44).astype(int)
    term_cover_multiple = has_term_insurance * np.random.uniform(5, 25, N)
    adequate_life_cover = (term_cover_multiple >= 10).astype(int)
    has_health_insurance = (np.random.random(N) < 0.61).astype(int)
    health_cover_lakhs = has_health_insurance * np.random.choice(
        [3, 5, 7, 10, 15, 25], p=[0.15, 0.30, 0.20, 0.20, 0.10, 0.05], size=N
    )

    # ── Investments ───────────────────────────────────────────────────────────
    invests_in_mf = (np.random.random(N) < 0.52).astype(int)
    invests_in_stocks = (np.random.random(N) < 0.34).astype(int)
    invests_in_fd = (np.random.random(N) < 0.71).astype(int)
    invests_in_ppf_nps = (np.random.random(N) < 0.38).astype(int)
    invests_in_gold = (np.random.random(N) < 0.46).astype(int)

    num_investment_types = (invests_in_mf + invests_in_stocks +
                            invests_in_fd + invests_in_ppf_nps + invests_in_gold)
    total_portfolio_value = (
        invests_in_mf * np.random.lognormal(12.5, 1.2, N) +
        invests_in_stocks * np.random.lognormal(11.5, 1.4, N) +
        invests_in_fd * np.random.lognormal(12.0, 1.0, N)
    )
    monthly_sip = invests_in_mf * np.random.lognormal(8.5, 0.9, N)
    equity_allocation_pct = np.random.beta(2.5, 2.5, N) * 100

    # ── Retirement Readiness ─────────────────────────────────────────────────
    years_to_retirement = (60 - age).clip(0, 38)
    has_epf = (np.random.random(N) < 0.68).astype(int)
    epf_corpus = has_epf * monthly_income * 0.12 * np.maximum(age - 22, 0) * 12 * 1.08
    fire_corpus_target = monthly_expenses * 12 * 25  # 25x annual expenses rule
    current_retirement_corpus = epf_corpus + total_portfolio_value * 0.4
    retirement_corpus_pct = (current_retirement_corpus / fire_corpus_target.clip(1)).clip(0, 2)

    # ── Compute Ground Truth Financial Health Score ───────────────────────────
    score_savings = np.clip(savings_rate / 0.30 * 100, 0, 100)
    score_emergency = emergency_months / 6 * 100
    score_debt = np.clip((1 - debt_to_income_ratio / 0.40) * 100, 0, 100)
    score_insurance = (adequate_life_cover * 50 + has_health_insurance * 50).clip(0, 100)
    score_diversification = (num_investment_types / 4 * 100).clip(0, 100)
    score_retirement = (retirement_corpus_pct * 100).clip(0, 100)

    # Weighted composite (matches PS9 specification)
    financial_health_score = (
        0.20 * score_savings +
        0.20 * score_emergency +
        0.15 * score_debt +
        0.15 * score_insurance +
        0.15 * score_diversification +
        0.15 * score_retirement
    ).clip(0, 100)

    # Add noise (real-world uncertainty)
    financial_health_score += np.random.normal(0, 3, N)
    financial_health_score = financial_health_score.clip(0, 100)

    # Categorical health tier
    health_tier = pd.cut(
        financial_health_score,
        bins=[0, 35, 55, 70, 85, 100],
        labels=['Critical', 'Poor', 'Fair', 'Good', 'Excellent']
    )

    df = pd.DataFrame({
        'age': age,
        'annual_income_lpa': income_lpa.round(2),
        'monthly_income': monthly_income.round(0),
        'monthly_expenses': monthly_expenses.round(0),
        'savings_rate': savings_rate.round(4),
        'monthly_savings': monthly_savings.round(0),
        'emergency_fund_months': emergency_months.round(2),
        'has_adequate_emergency_fund': has_adequate_emergency,
        'has_home_loan': has_home_loan,
        'has_car_loan': has_car_loan,
        'has_personal_loan': has_personal_loan,
        'has_credit_card_debt': has_credit_card_debt,
        'debt_to_income_ratio': debt_to_income_ratio.round(4),
        'credit_utilisation': credit_utilisation.round(4),
        'has_term_insurance': has_term_insurance,
        'term_cover_multiple': term_cover_multiple.round(1),
        'has_health_insurance': has_health_insurance,
        'health_cover_lakhs': health_cover_lakhs,
        'invests_in_mf': invests_in_mf,
        'invests_in_stocks': invests_in_stocks,
        'invests_in_fd': invests_in_fd,
        'invests_in_ppf_nps': invests_in_ppf_nps,
        'invests_in_gold': invests_in_gold,
        'num_investment_types': num_investment_types,
        'total_portfolio_value': total_portfolio_value.round(0),
        'monthly_sip': monthly_sip.round(0),
        'equity_allocation_pct': equity_allocation_pct.round(2),
        'years_to_retirement': years_to_retirement,
        'has_epf': has_epf,
        'epf_corpus': epf_corpus.round(0),
        'retirement_corpus_pct': retirement_corpus_pct.round(4),
        'score_savings': score_savings.round(2),
        'score_emergency': score_emergency.round(2),
        'score_debt': score_debt.round(2),
        'score_insurance': score_insurance.round(2),
        'score_diversification': score_diversification.round(2),
        'score_retirement': score_retirement.round(2),
        'financial_health_score': financial_health_score.round(2),
        'health_tier': health_tier
    })
    return df

kaggle_df, status = load_kaggle_data()
if status == 'kaggle':
    print('Using real Kaggle dataset')
    df = kaggle_df.copy()
else:
    df = generate_realistic_indian_finance_data(n=15000)
    print(f'✅ Generated realistic Indian finance dataset: {df.shape[0]:,} rows × {df.shape[1]} columns')


# ==========================================
# STEP 3: Exploratory Data Analysis (EDA)
# ==========================================
fig, axes = plt.subplots(1, 2, figsize=(14, 5))
fig.suptitle('AI Money Mentor — Financial Health Score Distribution', fontsize=14, fontweight='bold')

axes[0].hist(df['financial_health_score'], bins=50, color='#2563EB', alpha=0.8, edgecolor='white')
axes[0].set_xlabel('Financial Health Score (0–100)')
axes[0].set_ylabel('Count')
axes[0].set_title('Score Distribution')
axes[0].axvline(df['financial_health_score'].mean(), color='red', linestyle='--', label=f'Mean: {df["financial_health_score"].mean():.1f}')
axes[0].legend()

tier_counts = df['health_tier'].value_counts().reindex(['Critical','Poor','Fair','Good','Excellent'])
colors = ['#EF4444', '#F97316', '#EAB308', '#22C55E', '#10B981']
axes[1].bar(tier_counts.index, tier_counts.values, color=colors, edgecolor='white', linewidth=1.5)
axes[1].set_xlabel('Health Tier')
axes[1].set_ylabel('Count')
axes[1].set_title('Health Tier Distribution')
for i, v in enumerate(tier_counts.values):
    axes[1].text(i, v + 50, str(v), ha='center', fontsize=10, fontweight='bold')

plt.tight_layout()
plt.show()


# ==========================================
# STEP 4: Feature Engineering
# ==========================================
def engineer_features(df):
    df = df.copy()

    # Age-adjusted features
    recommended_equity_pct = (100 - df['age']).clip(20, 80)
    df['equity_vs_recommended'] = df['equity_allocation_pct'] - recommended_equity_pct

    # Wealth ratios
    df['portfolio_to_annual_income'] = (df['total_portfolio_value'] /
                                         (df['annual_income_lpa'] * 100000)).clip(0, 20)
    df['sip_to_income_ratio'] = (df['monthly_sip'] / df['monthly_income']).clip(0, 0.5)
    df['epf_to_income_ratio'] = (df['epf_corpus'] / (df['annual_income_lpa'] * 100000)).clip(0, 20)

    # Insurance adequacy
    df['insurance_adequacy_score'] = (
        (df['term_cover_multiple'] >= 10).astype(int) * 50 +
        (df['health_cover_lakhs'] >= 5).astype(int) * 30 +
        (df['health_cover_lakhs'] >= 10).astype(int) * 20
    )

    # Debt burden flag
    df['high_debt_burden'] = (df['debt_to_income_ratio'] > 0.40).astype(int)
    df['total_loans'] = df['has_home_loan'] + df['has_car_loan'] + df['has_personal_loan']

    # Savings momentum
    df['savings_above_30pct'] = (df['savings_rate'] >= 0.30).astype(int)
    df['savings_deficit'] = (0.30 - df['savings_rate']).clip(0, 0.30)

    # Financial maturity score
    df['financial_maturity'] = (
        df['invests_in_mf'] + df['invests_in_ppf_nps'] +
        df['has_term_insurance'] + df['has_health_insurance'] +
        df['has_epf'] + df['has_adequate_emergency_fund']
    )

    # Log transforms
    df['log_monthly_income'] = np.log1p(df['monthly_income'])
    df['log_total_portfolio'] = np.log1p(df['total_portfolio_value'])
    df['log_epf_corpus'] = np.log1p(df['epf_corpus'])

    # Interaction terms
    df['age_x_savings_rate'] = df['age'] * df['savings_rate']
    df['income_x_diversification'] = df['log_monthly_income'] * df['num_investment_types']

    return df

df_feat = engineer_features(df)
print(f'✅ Feature engineering complete. Shape: {df_feat.shape}')

REGRESSION_TARGET = 'financial_health_score'
CLASSIFICATION_TARGET = 'health_tier'
EXCLUDE_COLS = [
    'financial_health_score', 'health_tier',
    'score_savings', 'score_emergency', 'score_debt',
    'score_insurance', 'score_diversification', 'score_retirement'
]
FEATURE_COLS = [c for c in df_feat.columns if c not in EXCLUDE_COLS]


# ==========================================
# STEP 5: Train XGBoost Models
# ==========================================
X = df_feat[FEATURE_COLS].copy()
y_reg = df_feat[REGRESSION_TARGET]

le = LabelEncoder()
tier_order = ['Critical', 'Poor', 'Fair', 'Good', 'Excellent']
le.fit(tier_order)
y_clf = le.transform(df_feat[CLASSIFICATION_TARGET])

X_temp, X_test, y_reg_temp, y_reg_test, y_clf_temp, y_clf_test = train_test_split(
    X, y_reg, y_clf, test_size=0.15, random_state=42, stratify=y_clf
)
X_train, X_val, y_reg_train, y_reg_val, y_clf_train, y_clf_val = train_test_split(
    X_temp, y_reg_temp, y_clf_temp, test_size=0.176, random_state=42, stratify=y_clf_temp
)

# ── Regressor ──
xgb_reg_params = {
    'n_estimators': 800, 'max_depth': 6, 'learning_rate': 0.04,
    'subsample': 0.80, 'colsample_bytree': 0.80, 'min_child_weight': 3,
    'reg_alpha': 0.05, 'reg_lambda': 1.5, 'gamma': 0.1,
    'objective': 'reg:squarederror', 'eval_metric': 'rmse',
    'tree_method': 'hist', 'random_state': 42, 'n_jobs': -1
}

# Add early stopping here
xgb_regressor = xgb.XGBRegressor(**xgb_reg_params, early_stopping_rounds=50)
xgb_regressor.fit(X_train, y_reg_train, eval_set=[(X_val, y_reg_val)], verbose=False)

# ── Classifier ──
from collections import Counter
class_counts = Counter(y_clf_train)
total = len(y_clf_train)
class_weights = {cls: total / (len(class_counts) * count) for cls, count in class_counts.items()}
sample_weights = np.array([class_weights[y] for y in y_clf_train])

xgb_clf_params = {
    'n_estimators': 600, 'max_depth': 5, 'learning_rate': 0.05,
    'subsample': 0.80, 'colsample_bytree': 0.75, 'min_child_weight': 5,
    'reg_alpha': 0.1, 'reg_lambda': 2.0, 'objective': 'multi:softprob',
    'num_class': 5, 'eval_metric': 'mlogloss', 'tree_method': 'hist',
    'random_state': 42, 'n_jobs': -1
}

# Add early stopping here
xgb_classifier = xgb.XGBClassifier(**xgb_clf_params, early_stopping_rounds=40)
xgb_classifier.fit(X_train, y_clf_train, sample_weight=sample_weights, eval_set=[(X_val, y_clf_val)], verbose=False)


# ==========================================
# STEP 6: Optuna Hyperparameter Optimization
# ==========================================
import optuna
optuna.logging.set_verbosity(optuna.logging.WARNING)

def objective(trial):
    params = {
        'n_estimators': trial.suggest_int('n_estimators', 300, 1000),
        'max_depth': trial.suggest_int('max_depth', 3, 8),
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.15, log=True),
        'subsample': trial.suggest_float('subsample', 0.6, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.5, 1.0),
        'min_child_weight': trial.suggest_int('min_child_weight', 1, 10),
        'reg_alpha': trial.suggest_float('reg_alpha', 1e-3, 1.0, log=True),
        'reg_lambda': trial.suggest_float('reg_lambda', 0.5, 5.0),
        'gamma': trial.suggest_float('gamma', 0, 0.5),
        'objective': 'reg:squarederror', 'tree_method': 'hist',
        'random_state': 42, 'n_jobs': -1
    }

    # Initialize with early stopping here
    model = xgb.XGBRegressor(**params, early_stopping_rounds=30)
    model.fit(X_train, y_reg_train, eval_set=[(X_val, y_reg_val)], verbose=False)
    preds = model.predict(X_val)
    return mean_absolute_error(y_reg_val, preds)

print('🔍 Running Optuna hyperparameter search (50 trials)...')
study = optuna.create_study(direction='minimize')
study.optimize(objective, n_trials=50, show_progress_bar=True)

best_params = {**study.best_params, 'objective': 'reg:squarederror', 'tree_method': 'hist', 'random_state': 42, 'n_jobs': -1}

# Retrain optimal model with early stopping here
xgb_best = xgb.XGBRegressor(**best_params, early_stopping_rounds=50)
xgb_best.fit(X_train, y_reg_train, eval_set=[(X_val, y_reg_val)], verbose=False)

y_best_pred = xgb_best.predict(X_test)
rmse_best = np.sqrt(mean_squared_error(y_reg_test, y_best_pred))
mae_best = mean_absolute_error(y_reg_test, y_best_pred)
r2_best = r2_score(y_reg_test, y_best_pred)
roc_auc = roc_auc_score(y_clf_test, xgb_classifier.predict_proba(X_test), multi_class='ovr', average='weighted')


# ==========================================
# STEP 7: SHAP Explainability
# ==========================================
explainer = shap.TreeExplainer(xgb_best)
shap_values = explainer.shap_values(X_test)

plt.figure(figsize=(10, 7))
shap.summary_plot(shap_values, X_test, plot_type='bar', show=False, max_display=20, color='#2563EB')
plt.title('Top 20 Features by SHAP Importance', fontsize=12, fontweight='bold')
plt.show()


# ==========================================
# STEP 8: Save & Export Models
# ==========================================
import pickle
import json

xgb_best.save_model('/content/ai_money_mentor_regressor.json')
xgb_classifier.save_model('/content/ai_money_mentor_classifier.json')

with open('/content/model_metadata.pkl', 'wb') as f:
    pickle.dump({
        'label_encoder': le,
        'feature_cols': FEATURE_COLS,
        'tier_order': tier_order,
        'model_metrics': {
            'regressor_r2': float(r2_best),
            'regressor_mae': float(mae_best),
            'classifier_roc_auc': float(roc_auc)
        }
    }, f)

print('✅ Models and metadata saved successfully.')


# ==========================================
# STEP 9: Production Inference Pipeline
# ==========================================
class FinancialHealthScorer:
    def __init__(self, regressor_path: str, classifier_path: str, metadata_path: str):
        import xgboost as xgb
        import pickle
        import shap

        self.regressor = xgb.XGBRegressor()
        self.regressor.load_model(regressor_path)

        self.classifier = xgb.XGBClassifier()
        self.classifier.load_model(classifier_path)

        with open(metadata_path, 'rb') as f:
            meta = pickle.load(f)
        self.label_encoder = meta['label_encoder']
        self.feature_cols = meta['feature_cols']
        self.tier_order = meta['tier_order']

        self.explainer = shap.TreeExplainer(self.regressor)

    def preprocess(self, user_input: dict) -> pd.DataFrame:
        row = {
            'age': user_input.get('age', 30),
            'annual_income_lpa': user_input.get('annual_income_lpa', 8),
            'monthly_income': user_input.get('monthly_income', 66667),
            'monthly_expenses': user_input.get('monthly_expenses', 50000),
            'savings_rate': user_input.get('savings_rate', 0.25),
            'monthly_savings': user_input.get('monthly_savings', 16667),
            'emergency_fund_months': user_input.get('emergency_fund_months', 3),
            'has_adequate_emergency_fund': int(user_input.get('emergency_fund_months', 3) >= 6),
            'has_home_loan': int(user_input.get('has_home_loan', False)),
            'has_car_loan': int(user_input.get('has_car_loan', False)),
            'has_personal_loan': int(user_input.get('has_personal_loan', False)),
            'has_credit_card_debt': int(user_input.get('has_credit_card_debt', False)),
            'debt_to_income_ratio': user_input.get('debt_to_income_ratio', 0.0),
            'credit_utilisation': user_input.get('credit_utilisation', 0.0),
            'has_term_insurance': int(user_input.get('has_term_insurance', False)),
            'term_cover_multiple': user_input.get('term_cover_multiple', 0),
            'has_health_insurance': int(user_input.get('has_health_insurance', False)),
            'health_cover_lakhs': user_input.get('health_cover_lakhs', 0),
            'invests_in_mf': int(user_input.get('invests_in_mf', False)),
            'invests_in_stocks': int(user_input.get('invests_in_stocks', False)),
            'invests_in_fd': int(user_input.get('invests_in_fd', False)),
            'invests_in_ppf_nps': int(user_input.get('invests_in_ppf_nps', False)),
            'invests_in_gold': int(user_input.get('invests_in_gold', False)),
            'num_investment_types': sum([
                int(user_input.get('invests_in_mf', False)),
                int(user_input.get('invests_in_stocks', False)),
                int(user_input.get('invests_in_fd', False)),
                int(user_input.get('invests_in_ppf_nps', False)),
                int(user_input.get('invests_in_gold', False)),
            ]),
            'total_portfolio_value': user_input.get('total_portfolio_value', 0),
            'monthly_sip': user_input.get('monthly_sip', 0),
            'equity_allocation_pct': user_input.get('equity_allocation_pct', 40),
            'years_to_retirement': max(0, 60 - user_input.get('age', 30)),
            'has_epf': int(user_input.get('has_epf', False)),
            'epf_corpus': user_input.get('epf_corpus', 0),
            'retirement_corpus_pct': user_input.get('retirement_corpus_pct', 0.1),
        }
        df_row = pd.DataFrame([row])
        df_row = engineer_features(df_row)
        return df_row[self.feature_cols]

    def score(self, user_input: dict) -> dict:
        X_input = self.preprocess(user_input)

        score = float(self.regressor.predict(X_input)[0])
        score = round(max(0.0, min(100.0, score)), 1)  # type: ignore

        tier_proba = self.classifier.predict_proba(X_input)[0]
        tier_idx = tier_proba.argmax()
        tier = self.tier_order[tier_idx]
        tier_probabilities = {t: round(float(p) * 100.0, 1) for t, p in zip(self.tier_order, tier_proba)}

        shap_vals = self.explainer.shap_values(X_input)[0]
        shap_df = pd.DataFrame({
            'feature': self.feature_cols,
            'shap_value': shap_vals
        }).sort_values('shap_value', key=abs, ascending=False)

        top_positive = shap_df[shap_df['shap_value'] > 0].head(3)['feature'].tolist()
        top_negative = shap_df[shap_df['shap_value'] < 0].head(3)['feature'].tolist()

        recommendations = self._generate_recommendations(user_input, top_negative)

        return {
            'score': score,
            'tier': tier,
            'tier_probabilities': tier_probabilities,
            'top_positive_factors': top_positive,
            'top_negative_factors': top_negative,
            'recommendations': recommendations,
            'disclaimer': 'AI Analysis — Not Investment Advice. Consult a SEBI-registered advisor.'
        }

    def _generate_recommendations(self, user_input: dict, weak_features: list) -> list:
        recs = []
        em = user_input.get('emergency_fund_months', 0)
        if em < 6:
            recs.append(f'Build emergency fund from {em:.0f} → 6 months of expenses')
        if not user_input.get('has_term_insurance', False):
            income = user_input.get('annual_income_lpa', 8)
            cover = round(income * 10)
            recs.append(f'Get term life insurance of ₹{cover} LPA (10x income)')
        if not user_input.get('has_health_insurance', False):
            recs.append('Get health insurance (minimum ₹5 lakh family floater)')
        dr = user_input.get('debt_to_income_ratio', 0)
        if dr > 0.40:
            recs.append(f'Reduce EMI burden: {dr*100:.0f}% of income → target below 40%')
        sr = user_input.get('savings_rate', 0)
        if sr < 0.20:
            recs.append(f'Increase savings rate from {sr*100:.0f}% → 30% of income')
        if not recs:
            recs.append('Great financial health! Consider increasing equity allocation.')
        return recs[:3]  # type: ignore

# Demo: Scoring a sample user profile
scorer = FinancialHealthScorer(
    '/content/ai_money_mentor_regressor.json',
    '/content/ai_money_mentor_classifier.json',
    '/content/model_metadata.pkl'
)

ravi_profile = {
    'age': 34,
    'annual_income_lpa': 18,
    'monthly_income': 150000,
    'monthly_expenses': 95000,
    'savings_rate': 0.367,
    'monthly_savings': 55000,
    'emergency_fund_months': 3.5,
    'has_home_loan': True,
    'has_car_loan': False,
    'has_personal_loan': False,
    'has_credit_card_debt': False,
    'debt_to_income_ratio': 0.22,
    'credit_utilisation': 0.10,
    'has_term_insurance': False,
    'term_cover_multiple': 0,
    'has_health_insurance': True,
    'health_cover_lakhs': 10,
    'invests_in_mf': True,
    'invests_in_stocks': True,
    'invests_in_fd': True,
    'invests_in_ppf_nps': False,
    'invests_in_gold': True,
    'total_portfolio_value': 850000,
    'monthly_sip': 15000,
    'equity_allocation_pct': 62,
    'has_epf': True,
    'epf_corpus': 450000,
    'retirement_corpus_pct': 0.18,
}

print(scorer.score(ravi_profile))

